<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'category_id'       => 1,
                'sub_category_id'   => 1,
                'name'              => 'Wireless Headphones',
                'slug'              => Str::slug('Wireless Headphones'),
                'sku'               => 'WH-001',
                'price'             => 5500,
                'discount_price'    => 4999,
                'stock'             => 20,
                'short_description' => 'High quality wireless Bluetooth headphones.',
                'long_description'  => 'Comfortable wireless headphones with noise cancellation and long battery life.',
                'status'            => true,
                'featured'          => true,
            ],
            [
                'category_id'       => 1,
                'sub_category_id'   => 2,
                'name'              => 'Gaming Mouse',
                'slug'              => Str::slug('Gaming Mouse'),
                'sku'               => 'GM-002',
                'price'             => 2500,
                'discount_price'    => 1999,
                'stock'             => 50,
                'short_description' => 'RGB gaming mouse with fast response sensor.',
                'long_description'  => 'Ergonomic design, high DPI sensor, and multiple RGB lighting modes.',
                'status'            => true,
                'featured'          => false,
            ],
            [
                'category_id'       => 2,
                'sub_category_id'   => 3,
                'name'              => 'Men Cotton T-Shirt',
                'slug'              => Str::slug('Men Cotton T-Shirt'),
                'sku'               => 'TS-003',
                'price'             => 1200,
                'discount_price'    => 999,
                'stock'             => 100,
                'short_description' => 'Soft cotton t-shirt for daily wear.',
                'long_description'  => 'Premium quality cotton shirt suitable for summer season.',
                'status'            => true,
                'featured'          => false,
            ],
            [
                'category_id'       => 2,
                'sub_category_id'   => 4,
                'name'              => 'Women Stylish Handbag',
                'slug'              => Str::slug('Women Stylish Handbag'),
                'sku'               => 'HB-004',
                'price'             => 3500,
                'discount_price'    => 3200,
                'stock'             => 15,
                'short_description' => 'Elegant handbag for women.',
                'long_description'  => 'Trendy premium handbag perfect for all occasions.',
                'status'            => true,
                'featured'          => true,
            ],
            [
                'category_id'       => 3,
                'sub_category_id'   => 5,
                'name'              => 'Stainless Steel Water Bottle',
                'slug'              => Str::slug('Stainless Steel Water Bottle'),
                'sku'               => 'WB-005',
                'price'             => 900,
                'discount_price'    => 750,
                'stock'             => 60,
                'short_description' => 'Keep beverages hot or cold.',
                'long_description'  => 'Durable stainless steel insulated water bottle.',
                'status'            => true,
                'featured'          => false,
            ],
            [
                'category_id'       => 3,
                'sub_category_id'   => 6,
                'name'              => 'LED Desk Lamp',
                'slug'              => Str::slug('LED Desk Lamp'),
                'sku'               => 'DL-006',
                'price'             => 1800,
                'discount_price'    => 1500,
                'stock'             => 30,
                'short_description' => 'Energy efficient LED desk lamp.',
                'long_description'  => 'Adjustable brightness and flexible neck LED lamp.',
                'status'            => true,
                'featured'          => true,
            ],
            [
                'category_id'       => 1,
                'sub_category_id'   => 2,
                'name'              => 'Mechanical Keyboard',
                'slug'              => Str::slug('Mechanical Keyboard'),
                'sku'               => 'MK-007',
                'price'             => 6000,
                'discount_price'    => 5500,
                'stock'             => 40,
                'short_description' => 'RGB backlit mechanical keyboard.',
                'long_description'  => 'Blue switches, compact design, and customizable lighting.',
                'status'            => true,
                'featured'          => false,
            ],
            [
                'category_id'       => 4,
                'sub_category_id'   => 7,
                'name'              => 'Sports Running Shoes',
                'slug'              => Str::slug('Sports Running Shoes'),
                'sku'               => 'RS-008',
                'price'             => 5200,
                'discount_price'    => 4800,
                'stock'             => 25,
                'short_description' => 'Comfortable running shoes.',
                'long_description'  => 'Breathable and lightweight shoes ideal for jogging.',
                'status'            => true,
                'featured'          => true,
            ],
            [
                'category_id'       => 5,
                'sub_category_id'   => 8,
                'name'              => 'Wooden Study Table',
                'slug'              => Str::slug('Wooden Study Table'),
                'sku'               => 'ST-009',
                'price'             => 8500,
                'discount_price'    => 7999,
                'stock'             => 10,
                'short_description' => 'Strong wooden study table.',
                'long_description'  => 'High quality polished wood, ideal for home office.',
                'status'            => true,
                'featured'          => false,
            ],
            [
                'category_id'       => 5,
                'sub_category_id'   => 9,
                'name'              => 'Comfort Office Chair',
                'slug'              => Str::slug('Comfort Office Chair'),
                'sku'               => 'OC-010',
                'price'             => 9500,
                'discount_price'    => 9000,
                'stock'             => 12,
                'short_description' => 'Ergonomic office chair.',
                'long_description'  => 'Mesh back support with adjustable height and wheels.',
                'status'            => true,
                'featured'          => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
